plugins {
    id("java")
    id("org.jetbrains.intellij") version "1.16.1"
    id("org.jetbrains.grammarkit") version "2022.3.2"
}

group = "com.linuxgods.kreiger.idea.jmte"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.floreysoft:jmte:7.0.0'
}

// Configure Gradle IntelliJ Plugin
// Read more: https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html
intellij {
    version = "2023.2.5"
    type = "IC" // Target IDE Platform

    plugins = ['com.intellij.java', 'maven',
               'org.jusecase.jte-intellij:2.1.2',
               'org.jetbrains.plugins.go-template:232.9921.89',
               'PsiViewer:232.2',
               'com.dmarcotte.handlebars:232.8660.88',
              // 'com.intellij.freemarker', 'com.intellij.velocity'
    ]
    updateSinceUntilBuild = false
}

tasks.generateLexer {
    sourceFile = file("src/main/resources/Jmte.flex")
    targetClass = "com.linuxgods.kreiger.idea.jmte._JmteLexer"
    targetDir = "build/generated/lexer/com/linuxgods/kreiger/idea/jmte"
    dependsOn cleanGenerateLexer
}
tasks.generateParser {
    sourceFile = file("src/main/resources/Jmte.bnf")
    pathToParser = "_JmteParser"
    pathToPsiRoot = "psi"
    targetRoot = "build/generated/parser"
    dependsOn cleanGenerateParser
}
sourceSets.main.java.srcDirs += file("build/generated/lexer")
sourceSets.main.java.srcDirs += file("build/generated/parser")


tasks.withType(JavaCompile) {
    options.release = 17
    dependsOn tasks.generateLexer
    dependsOn tasks.generateParser
}

runIde {
    jvmArgs '-Xmx4G'
}