{
  parserClass="com.linuxgods.kreiger.idea.jmte.JmteParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Jmte"
  psiImplClassSuffix="Impl"
  psiPackage="com.linuxgods.kreiger.idea.jmte.psi"
  psiImplPackage="com.linuxgods.kreiger.idea.jmte.psi.impl"

  elementTypeHolderClass="com.linuxgods.kreiger.idea.jmte.psi.JmteTypes"
  elementTypeClass="com.linuxgods.kreiger.idea.jmte.psi.JmteElementType"
  tokenTypeClass="com.linuxgods.kreiger.idea.jmte.psi.JmteTokenType"
}

jmteFile ::= content_or_template*

private content_or_template ::= content | template

private template ::= if_block | foreach_block | comment_tag | annotation_tag | string_tag

content ::= TEMPLATE_DATA_TOKEN { consumeTokenMethod="consumeTokenFast" }

//private recover ::= ! text
//private recover ::= ! END_TOKEN
//private recover ::= START_TOKEN

comment_tag ::= <<tag comment?>> {name="${--...}"}

comment ::= comment_keyword comment_token { pin=1 }

private comment_keyword ::= COMMENT_KEYWORD_TOKEN {name="--"}

private comment_token ::= COMMENT_TOKEN

end_tag ::= <<tag end_keyword>> {name="${end}"}

private end_keyword ::= END_KEYWORD_TOKEN {name="end_tag"}

if_block ::= if_tag content_or_template* (else_tag content_or_template*)? end_tag

if_tag ::= <<tag if>> {name="${if ...}"}

if ::= if_keyword condition { pin=1 recoverWhile=not_end_token }

private if_keyword ::= IF_KEYWORD_TOKEN {name="if_tag"}

quoted_string ::= QUOTE_TOKEN string? QUOTE_TOKEN

condition_operand_tag ::= annotation | if | else_keyword | foreach | end_tag | string_expression

condition_operand ::= quoted_string | condition_operand_tag

condition ::= NOT_TOKEN? (expression (EQUALS_TOKEN condition_operand)?)

else_tag ::= <<tag else_keyword>> {name="${else}"}

private else_keyword ::= ELSE_KEYWORD_TOKEN {name="else_tag"}

foreach_block ::= foreach_tag content_or_template* end_tag

foreach_tag ::= <<tag foreach >> {name="${foreach ...}"}

foreach ::= foreach_keyword foreach_parameters { pin=1 recoverWhile=not_end_token }

foreach_parameters ::= expression (identifier foreach_separator)?

private foreach_separator ::= content

private foreach_keyword ::= FOREACH_KEYWORD_TOKEN {name="foreach_tag"}

annotation_tag ::= <<tag annotation>> {name="${@...}"}

annotation ::= annotation_keyword annotation_receiver annotation_arguments {
    extends="com.linuxgods.kreiger.idea.jmte.psi.JmteAnnotationBase"
    pin=1
}

private annotation_keyword ::= ANNOTATION_KEYWORD_TOKEN {name="@"}

private annotation_receiver ::= identifier

private annotation_arguments ::= USER_DEFINED_TOKEN

string_tag ::= <<tag string_expression >> {
    methods=[prefix="/[0]/affixed/content[0]" suffix="/[0]/affixed/content[1]"]
    name="${...}"
}

private string_expression ::= (affixed | unaffixed) format? { pin=1 recoverWhile=not_end_token }

private semi_colon ::= SEMI_COLON_TOKEN {name=";"}

affixed ::= content comma unaffixed comma content

private comma ::= COMMA_TOKEN {name=","}

unaffixed ::= expression defaultValue? {extends=unaffixed}

string ::= STRING_TOKEN? {
    extends="com.linuxgods.kreiger.idea.jmte.psi.JmteStringBase"
    implements="com.intellij.psi.PsiLanguageInjectionHost"
}

format ::= semi_colon identifier format_params? {name=";format(parameters)"}

defaultValue ::= left_paren content right_paren {name="(default value)"}

format_params ::= left_paren USER_DEFINED_TOKEN right_paren {name="(format parameters)"}

private left_paren ::= LEFT_PAREN_TOKEN {name="("}
private right_paren ::= RIGHT_PAREN_TOKEN {name=")"}

expression ::= qualifier_expression

qualifier_expression ::= qualified_expression | simple_reference_expression {extends=expression}

fake reference_expression ::= qualifier_expression? DOT_TOKEN identifier {extends=qualifier_expression}

qualified_expression ::= qualifier_expression DOT_TOKEN identifier {extends=reference_expression elementType=reference_expression}

simple_reference_expression ::= identifier {elementType=reference_expression}

identifier ::= IDENTIFIER_TOKEN {
    extends="com.linuxgods.kreiger.idea.jmte.psi.JmteIdentifierBase"
}

private meta tag ::= start_token <<t>> end_token {name="tag"}
private start_token ::= START_TOKEN {name="${" }
private end_token ::= END_TOKEN {name="}" }
private not_end_token ::= !END_TOKEN
