{
  parserClass="com.linuxgods.kreiger.idea.jmte.JmteParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Jmte"
  psiImplClassSuffix="Impl"
  psiPackage="com.linuxgods.kreiger.idea.jmte.psi"
  psiImplPackage="com.linuxgods.kreiger.idea.jmte.psi.impl"

  elementTypeHolderClass="com.linuxgods.kreiger.idea.jmte.psi.JmteTypes"
  elementTypeClass="com.linuxgods.kreiger.idea.jmte.psi.JmteElementType"
  tokenTypeClass="com.linuxgods.kreiger.idea.jmte.psi.JmteTokenType"
}

jmteFile ::= template_*

private template_ ::= text | comment | if_block | foreach_block | string_expression

text ::= TEMPLATE_DATA_TOKEN

private recover ::= !text

comment ::= START_TOKEN COMMENT_TOKEN? END_TOKEN

end_expression ::= START_TOKEN END_KEYWORD_TOKEN END_TOKEN

if_block ::= if_expression template_* (elseif template_*)* (else template_*)? end_expression

if_expression ::= START_TOKEN IF_KEYWORD_TOKEN condition END_TOKEN

condition ::= NOT_TOKEN? (expression (EQUALS_TOKEN string)?)

else ::= START_TOKEN ELSE_KEYWORD_TOKEN END_TOKEN

elseif ::= START_TOKEN ELSEIF_KEYWORD_TOKEN condition END_TOKEN

foreach_block ::= START_TOKEN FOREACH_KEYWORD_TOKEN expression (identifier string?)? END_TOKEN template_* end_expression

string_expression ::= START_TOKEN (string COMMA_TOKEN expression defaultValue? COMMA_TOKEN string | expression defaultValue?) (SEMI_COLON_TOKEN format)? END_TOKEN {
    methods=[prefix="/[1]/string[0]" suffix="/[1]/string[1]"] 
}

string ::= STRING_TOKEN?

format ::= identifier param?

private defaultValue ::= LEFT_PAREN_TOKEN string RIGHT_PAREN_TOKEN

private param ::= LEFT_PAREN_TOKEN string RIGHT_PAREN_TOKEN

expression ::= qualifier_expression

qualifier_expression ::= qualified_reference_expression | simple_reference_expression {extends=expression}

fake reference_expression ::= qualifier_expression? DOT_TOKEN identifier {extends=qualifier_expression}

qualified_reference_expression ::= qualifier_expression DOT_TOKEN identifier {extends=reference_expression elementType=reference_expression}

simple_reference_expression ::= identifier {elementType=reference_expression}

identifier ::= IDENTIFIER_TOKEN
